services:
  docker-login:
    image: alpine:latest
    environment:
      - DOCKER_CLI_ACI=1

  database:
    image: postgres
    hostname: db
    environment:
      DB_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      DB_NAME: dotnet-template
    ports:
      - 5432:5432
